/*
Package store GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package store

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&GetStoreBlob{}))
}

func (*GetStoreBlob) ResponseContent() any {
	return new(string)
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&UploadStoreBlob{}))
}

func (*UploadStoreBlob) ResponseContent() any {
	return nil
}
