// Code generated by gengo:taggedunion DO NOT EDIT.
package v1

import (
	bytes "bytes"

	jsonjsontext "github.com/go-json-experiment/json/jsontext"

	validator "github.com/octohelm/courier/pkg/validator"
	taggedunion "github.com/octohelm/courier/pkg/validator/taggedunion"
)

func (Union) Discriminator() string {
	return "kind"
}

func (Union) Mapping() map[string]any {
	return map[string]any{
		"String": new(StringKinded),
		"Bool":   new(BoolKinded),
	}
}

func (u *Union) SetUnderlying(v any) {
	switch x := v.(type) {
	case *StringKinded:
		u.String = x
	case *BoolKinded:
		u.Bool = x

	}
}

func (u *Union) Underlying() Kinded {
	if u.String != nil {
		return u.String
	}
	if u.Bool != nil {
		return u.Bool
	}

	return nil
}

func (u *Union) IsZero() bool {
	return u.String == nil && u.Bool == nil
}

func (u Union) MarshalJSON() ([]byte, error) {
	if u.Underlying() == nil {
		return []byte("{}"), nil
	}
	return validator.Marshal(u.Underlying())
}

func (u *Union) UnmarshalJSON(data []byte) error {
	mm := Union{}
	if err := taggedunion.UnmarshalDecode(jsonjsontext.NewDecoder(bytes.NewBuffer(data)), &mm); err != nil {
		return err
	}
	*u = mm
	return nil
}
