/*
Package httprequest GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package httprequest

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (Params) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
