download:
	wget -O ./2020-12/schema.json https://json-schema.org/draft/2020-12/schema
	wget -O ./2020-12/meta/core.json https://json-schema.org/draft/2020-12/meta/core
	wget -O ./2020-12/meta/applicator.json https://json-schema.org/draft/2020-12/meta/applicator
	wget -O ./2020-12/meta/unevaluated.json https://json-schema.org/draft/2020-12/meta/unevaluated
	wget -O ./2020-12/meta/validation.json https://json-schema.org/draft/2020-12/meta/validation
	wget -O ./2020-12/meta/meta-data.json https://json-schema.org/draft/2020-12/meta/meta-data
	wget -O ./2020-12/meta/format-annotation.json https://json-schema.org/draft/2020-12/meta/format-annotation
	wget -O ./2020-12/meta/content.json https://json-schema.org/draft/2020-12/meta/content
