/*
Package openapi GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package openapi

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (BuildFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (BuildOptionFunc) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (PkgNamingPrefix) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
