/*
Package extractors GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package extractors

func (*FieldExclude) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (v *FieldFilter) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Exclude":
			return []string{}, true
		case "Include":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v *Opt) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Decl":
			return []string{}, true
		case "Doc":
			return []string{}, true
		case "EnumInDoc":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (*TypeName) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
