/*
Package extractors GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package extractors

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (FieldExclude) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (v FieldFilter) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Exclude":
			return []string{}, true
		case "Include":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v Opt) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Decl":
			return []string{}, true
		case "Doc":
			return []string{}, true
		case "EnumInDoc":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

func (v StructField) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "StructField":
			return []string{}, true
		case "DisplayName":
			return []string{}, true
		case "Optional":
			return []string{}, true

		}
		if doc, ok := runtimeDoc(v.StructField, names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{}, true
}

func (TypeName) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
