// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *List[T]) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Items":
			return []string{
				"列表",
			}, true
		case "Total":
			return []string{
				"总数",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示通用列表返回。",
	}, true
}

func (v *Pager) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Offset":
			return []string{
				"偏移量",
			}, true
		case "Limit":
			return []string{
				"单次拉取条数，默认 10，最大 50",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示通用分页参数。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
