// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *CreateOrg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Body":
			return []string{
				"创建参数",
			}, true
		}

		return nil, false
	}
	return []string{
		"创建组织",
	}, true
}

func (v *DeleteOrg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"组织 ID",
			}, true
		}

		return nil, false
	}
	return []string{
		"删除组织",
	}, true
}

func (v *GetOrg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"组织 ID",
			}, true
		}

		return nil, false
	}
	return []string{
		"查询组织信息",
	}, true
}

func (v *ListOrg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"按组织 ID 过滤",
			}, true
		case "OrgName":
			return []string{
				"按组织名称过滤",
			}, true
		case "OrgType":
			return []string{
				"按组织类型过滤",
			}, true

		}
		if doc, ok := runtimeDoc(&v.Pager, "", names...); ok {
			return doc, ok
		}

		return nil, false
	}
	return []string{
		"拉取组织列表",
	}, true
}

func (v *UpdateOrg) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"组织 ID",
			}, true
		case "Body":
			return []string{
				"更新参数",
			}, true

		}

		return nil, false
	}
	return []string{
		"更新组织",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
