// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *ErrOrgNameConflict) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgName":
			return []string{
				"已存在的组织名称",
			}, true
		}

		return nil, false
	}
	return []string{
		"表示组织名称冲突。",
	}, true
}

func (v *ErrOrgNotFound) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"查询时使用的组织 ID",
			}, true
		case "OrgName":
			return []string{
				"查询时使用的组织名称",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示组织不存在。",
	}, true
}

func (v *Org) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "ID":
			return []string{
				"组织 ID",
			}, true
		case "CreatedAt":
			return []string{
				"创建时间",
			}, true
		case "UpdatedAt":
			return []string{
				"更新时间",
			}, true
		case "Spec":
			return []string{
				"组织规格",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示组织对象。",
	}, true
}

func (v *OrgForCreateRequest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Spec":
			return []string{
				"待创建的组织规格",
			}, true
		}

		return nil, false
	}
	return []string{
		"表示创建组织请求体。",
	}, true
}

func (v *OrgForListRequest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "OrgID":
			return []string{
				"按组织 ID 过滤",
			}, true
		case "OrgName":
			return []string{
				"按组织名称过滤",
			}, true
		case "OrgType":
			return []string{
				"按组织类型过滤",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示组织列表查询条件。",
	}, true
}

func (v *OrgForUpdateRequest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Spec":
			return []string{
				"待更新的组织规格",
			}, true
		}

		return nil, false
	}
	return []string{
		"表示更新组织请求体。",
	}, true
}

func (*OrgID) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

func (*OrgName) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示组织名称。",
	}, true
}

func (v *OrgSpec) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Name":
			return []string{
				"组织名称",
			}, true
		case "Type":
			return []string{
				"组织类型",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示组织规格。",
	}, true
}

func (*OrgType) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
