/*
Package blob GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package blob

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&UploadBlob{}))
}

func (*UploadBlob) ResponseContent() any {
	return nil
}
