/*
Package blob GENERATED BY gengo:operator
DON'T EDIT THIS FILE
*/
package blob

import (
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&GetFile{}))
}

func (*GetFile) ResponseContent() any {
	return new(string)
}

func (*GetFile) ResponseData() *string {
	return new(string)
}

func init() {
	R.Register(courier.NewRouter(&UploadBlob{}))
}

func (*UploadBlob) ResponseContent() any {
	return nil
}

func (*UploadBlob) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}
