// Code generated by gengo:injectable DO NOT EDIT.
package v1

import (
	context "context"
	fmt "fmt"

	orgservice "github.com/octohelm/courier/internal/example/domain/org/service"
)

func (v *CreateOrg) Init(ctx context.Context) error {
	if value, ok := orgservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *DeleteOrg) Init(ctx context.Context) error {
	if value, ok := orgservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *GetOrg) Init(ctx context.Context) error {
	if value, ok := orgservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *ListOrg) Init(ctx context.Context) error {
	if value, ok := orgservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *UpdateOrg) Init(ctx context.Context) error {
	if value, ok := orgservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}
