// Code generated by gengo:operator DO NOT EDIT.
package v1

import (
	orgv1 "github.com/octohelm/courier/internal/example/pkg/apis/org/v1"
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&CreateOrg{}))
}

func (CreateOrg) ResponseContent() any {
	return new(orgv1.Org)
}

func init() {
	R.Register(courier.NewRouter(&DeleteOrg{}))
}

func (DeleteOrg) ResponseContent() any {
	return nil
}

func init() {
	R.Register(courier.NewRouter(&GetOrg{}))
}

func (GetOrg) ResponseContent() any {
	return new(orgv1.Org)
}

func init() {
	R.Register(courier.NewRouter(&ListOrg{}))
}

func (ListOrg) ResponseContent() any {
	return new(orgv1.OrgList)
}

func init() {
	R.Register(courier.NewRouter(&UpdateOrg{}))
}

func (UpdateOrg) ResponseContent() any {
	return new(orgv1.Org)
}
