/*
Package statuserror GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package statuserror

import _ "embed"

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v *ErrorResponse) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Code":
			return []string{}, true
		case "Key":
			return []string{}, true
		case "Msg":
			return []string{}, true
		case "Location":
			return []string{}, true
		case "Pointer":
			return []string{}, true
		case "Source":
			return []string{}, true
		case "Errors":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}
