// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *DeleteBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"内容摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示删除 blob。",
	}, true
}

func (v *DeleteManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"manifest 摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示删除 manifest。",
	}, true
}

func (v *GetBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"内容摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示拉取 blob。",
	}, true
}

func (v *GetManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"manifest 摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示拉取 manifest。",
	}, true
}

func (v *PutManifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"manifest 摘要",
			}, true
		case "Body":
			return []string{
				"manifest 内容",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示写入 manifest。",
	}, true
}

func (v *UploadBlob) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"仓库命名空间",
			}, true
		case "Body":
			return []string{
				"二进制内容",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示上传 blob。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
