// Code generated by gengo:runtimedoc DO NOT EDIT.
package v1

func (v *Descriptor) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "MediaType":
			return []string{
				"媒体类型",
			}, true
		case "Digest":
			return []string{
				"内容摘要",
			}, true
		case "Size":
			return []string{
				"内容大小",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示对象描述信息。",
	}, true
}

func (*Digest) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示内容摘要。",
	}, true
}

func (v *ErrBlobNotFound) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"对应仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"对应内容摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示 blob 不存在。",
	}, true
}

func (v *ErrManifestInvalid) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Reason":
			return []string{
				"错误原因",
			}, true
		}

		return nil, false
	}
	return []string{
		"表示 manifest 内容非法。",
	}, true
}

func (v *ErrManifestNotFound) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Namespace":
			return []string{
				"对应仓库命名空间",
			}, true
		case "Digest":
			return []string{
				"对应 manifest 摘要",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示 manifest 不存在。",
	}, true
}

func (v *Manifest) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Config":
			return []string{
				"配置对象描述",
			}, true
		case "Assets":
			return []string{
				"资源对象描述列表",
			}, true

		}

		return nil, false
	}
	return []string{
		"表示镜像清单。",
	}, true
}

func (*MediaType) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示对象媒体类型。",
	}, true
}

func (*Namespace) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{
		"表示仓库命名空间。",
	}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
