/*
Package org GENERATED BY gengo:operator 
DON'T EDIT THIS FILE
*/
package org

import (
	github_com_octohelm_courier_pkg_courier "github.com/octohelm/courier/pkg/courier"
	github_com_octohelm_courier_pkg_statuserror "github.com/octohelm/courier/pkg/statuserror"
)

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&Cookie{}))
}

func (*Cookie) ResponseContent() any {
	return new(any)
}

func (*Cookie) ResponseData() *any {
	return new(any)
}
func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&CreateOrg{}))
}

func (*CreateOrg) ResponseContent() any {
	return nil
}

func (*CreateOrg) ResponseData() *github_com_octohelm_courier_pkg_courier.NoContent {
	return new(github_com_octohelm_courier_pkg_courier.NoContent)
}
func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&DeleteOrg{}))
}

func (*DeleteOrg) ResponseContent() any {
	return nil
}

func (*DeleteOrg) ResponseData() *github_com_octohelm_courier_pkg_courier.NoContent {
	return new(github_com_octohelm_courier_pkg_courier.NoContent)
}
func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&GetOrg{}))
}

func (*GetOrg) ResponseContent() any {
	return new(Detail)
}

func (*GetOrg) ResponseData() *Detail {
	return new(Detail)
}
func (*GetOrg) ResponseErrors() []error {
	return []error{
		&(github_com_octohelm_courier_pkg_statuserror.StatusErr{
			Code: 404,
			Key:  "org.ErrNotFound",
			Msg:  "{OrgName}: 组织不存在",
		}),
	}
}

func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListOrg{}))
}

func (*ListOrg) ResponseContent() any {
	return new(DataList[Info])
}

func (*ListOrg) ResponseData() *DataList[Info] {
	return new(DataList[Info])
}
func init() {
	R.Register(github_com_octohelm_courier_pkg_courier.NewRouter(&ListOrgOld{}))
}

func (*ListOrgOld) ResponseContent() any {
	return new(any)
}

func (*ListOrgOld) ResponseData() *any {
	return new(any)
}
