// Code generated by gengo:operator DO NOT EDIT.
package v1

import (
	storev1 "github.com/octohelm/courier/internal/example/pkg/apis/store/v1"
	courier "github.com/octohelm/courier/pkg/courier"
)

func init() {
	R.Register(courier.NewRouter(&DeleteBlob{}))
}

func (DeleteBlob) ResponseContent() any {
	return new(storev1.Descriptor)
}

func (DeleteBlob) ResponseData() *storev1.Descriptor {
	return new(storev1.Descriptor)
}

func init() {
	R.Register(courier.NewRouter(&DeleteManifest{}))
}

func (DeleteManifest) ResponseContent() any {
	return nil
}

func (DeleteManifest) ResponseData() *courier.NoContent {
	return new(courier.NoContent)
}

func init() {
	R.Register(courier.NewRouter(&GetBlob{}))
}

func init() {
	R.Register(courier.NewRouter(&GetManifest{}))
}

func (GetManifest) ResponseContent() any {
	return new(storev1.Manifest)
}

func (GetManifest) ResponseData() *storev1.Manifest {
	return new(storev1.Manifest)
}

func init() {
	R.Register(courier.NewRouter(&PutManifest{}))
}

func (PutManifest) ResponseContent() any {
	return new(storev1.Descriptor)
}

func (PutManifest) ResponseData() *storev1.Descriptor {
	return new(storev1.Descriptor)
}

func init() {
	R.Register(courier.NewRouter(&UploadBlob{}))
}

func (UploadBlob) ResponseContent() any {
	return new(storev1.Descriptor)
}

func (UploadBlob) ResponseData() *storev1.Descriptor {
	return new(storev1.Descriptor)
}
