// Code generated by gengo:injectable DO NOT EDIT.
package v1

import (
	context "context"
	fmt "fmt"

	storeservice "github.com/octohelm/courier/internal/example/domain/store/service"
)

func (v *DeleteBlob) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *DeleteManifest) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *GetBlob) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *GetManifest) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *PutManifest) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}

func (v *UploadBlob) Init(ctx context.Context) error {
	if value, ok := storeservice.ServiceFromContext(ctx); ok {
		v.svc = value
	} else {
		return fmt.Errorf("missing provider %T.svc", v)
	}

	return nil
}
