/*
Package courierhttp GENERATED BY gengo:injectable 
DON'T EDIT THIS FILE
*/
package courierhttp

import (
	context "context"
)

type contextHttpRequest struct{}

func HttpRequestFromContext(ctx context.Context) (*HttpRequest, bool) {
	if v, ok := ctx.Value(contextHttpRequest{}).(*HttpRequest); ok {
		return v, true
	}
	return nil, false
}

func HttpRequestInjectContext(ctx context.Context, tpe *HttpRequest) context.Context {
	return context.WithValue(ctx, contextHttpRequest{}, tpe)
}

func (v *HttpRequest) Init(ctx context.Context) error {

	return nil
}

type contextOperationInfo struct{}

func OperationInfoFromContext(ctx context.Context) (*OperationInfo, bool) {
	if v, ok := ctx.Value(contextOperationInfo{}).(*OperationInfo); ok {
		return v, true
	}
	return nil, false
}

func OperationInfoInjectContext(ctx context.Context, tpe *OperationInfo) context.Context {
	return context.WithValue(ctx, contextOperationInfo{}, tpe)
}

func (v *OperationInfo) Init(ctx context.Context) error {

	return nil
}
