// Code generated by gengo:injectable DO NOT EDIT.
package service

import (
	context "context"
)

type contextService struct{}

func ServiceFromContext(ctx context.Context) (Service, bool) {
	if v, ok := ctx.Value(contextService{}).(Service); ok {
		return v, true
	}
	return nil, false
}

func ServiceInjectContext(ctx context.Context, tpe Service) context.Context {
	return context.WithValue(ctx, contextService{}, tpe)
}
