name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: "jsonv2"

    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v2
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.25'

      - run: just test-race


